apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  nfs:
    server: 172.23.171.172
    path: /data/nfs/gitlab/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 172.23.171.172
    path: /data/nfs/gitlab/redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postsql-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 172.23.171.172
    path: /data/nfs/gitlab/postsql

---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: gitlab-data-pv 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-redis-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: gitlab-redis-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-postsql-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: gitlab-postsql-pv