apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: monitoring
type: Opaque
data:
  # 把你的 AK/SK 做 base64 编码后填入
  accessKey: em1tbXRoS3BZSHdIcmw1VVFJdWEK
  secretKey: eElMNUt1Vkx1QlFkZnlZV2NOdVhTNGR0dE4zMXBUT0xKQTJJMTRxaQo=