apiVersion: v1
kind: Pod
metadata:
  name: dapi-envar-container
spec:
  containers:
  - name: dapi-envar-container
    image: docker.m.daocloud.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh","-c"]
    args:
    - while true; do echo -en '\n';
      printenv MY_CPU_REQUEST MY_CPU_LIMIT MY_MEMORY_REQUEST MY_MEMORY_LIMIT;
      sleep 10;
      done
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    env: 
    - name: MY_CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: dapi-envar-container
          resource: requests.cpu
    - name: MY_CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: dapi-envar-container
          resource: limits.cpu
    - name: MY_MEMORY_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: dapi-envar-container
          resource: requests.memory
    - name: MY_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: dapi-envar-container
          resource: limits.memory
  restartPolicy: Never