apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: docker.m.daocloud.io/nginx:latest
    ports:
    - containerPort: 80
    env: 
    - name: GET_HOSTS_FROM
      value: env