apiVersion: v1
kind: Pod
metadata:
  name: frontend-redis
  labels:
    app: frontend-redis
spec:
  containers:
  - name: frontend
    image: docker.m.daocloud.io/nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    env: 
    - name: GET_HOSTS_FROM
      value: env
  - name: redis
    image: docker.m.daocloud.io/redis:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
  - name: busybox
    image: docker.m.daocloud.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "3600"]