apiVersion: v1
kind: Pod
metadata: 
  name: init-container-example
  labels:
    app: "init-container-example"

spec:
  initContainers: 
  - name: init-myservice
    image: docker.m.daocloud.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo 初始化第一步']
  - name: init-myservice2
    image: docker.m.daocloud.io/busybox:latest  
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo 初始化第二步；'] 
  - name: init-myservice3
    image: docker.m.daocloud.io/busybox:latest  
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo 初始化第三步；']
  containers:
  - name: nginx
    image: docker.m.daocloud.io/nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80