apiVersion: v1 
kind: Pod
metadata:
  name: nginx-init-containers
  labels:
    app: "nginx"
    announce: "init-containers"
spec:
  initContainers:
  - name: init-install
    image: docker.m.daocloud.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: 
    - wget
    - "-O"
    - "/work-dir/index.html"
    - "https://kubernetes.io"
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  containers:
  - name: nginx
    image: docker.m.daocloud.io/nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}