apiVersion: v1
kind: Pod
metadata:
  name: node-ani-affinity
spec:
  containers:
  - name: nginx
    image: docker.m.daocloud.io/nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nginx
        topologyKey: kubernetes.io/hostname